/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 nam90.gltf
Author: StudioAira! (https://sketchfab.com/studioaira)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/nike-air-max-90-f1d3988d09dc47e88cb3e08c104c5461
Title: Nike Air Max 90
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/nam90.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={0.77} />
    </group>
  )
}

useGLTF.preload('/nam90.gltf')
